// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_CONTACTSTOPPEERS
#define LQTG_TYPE_CONTACTSTOPPEERS

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QList>
#include "toppeercategorypeers.h"
#include "chat.h"
#include "user.h"

class LIBQTELEGRAMSHARED_EXPORT ContactsTopPeers : public TelegramTypeObject
{
public:
    enum ContactsTopPeersClassType {
        typeContactsTopPeersNotModified = 0xde266ef5,
        typeContactsTopPeers = 0x70b772a8
    };

    ContactsTopPeers(ContactsTopPeersClassType classType = typeContactsTopPeersNotModified, InboundPkt *in = 0);
    ContactsTopPeers(InboundPkt *in);
    ContactsTopPeers(const Null&);
    virtual ~ContactsTopPeers();

    void setCategories(const QList<TopPeerCategoryPeers> &categories);
    QList<TopPeerCategoryPeers> categories() const;

    void setChats(const QList<Chat> &chats);
    QList<Chat> chats() const;

    void setUsers(const QList<User> &users);
    QList<User> users() const;

    void setClassType(ContactsTopPeersClassType classType);
    ContactsTopPeersClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    bool operator ==(const ContactsTopPeers &b) const;

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    QList<TopPeerCategoryPeers> m_categories;
    QList<Chat> m_chats;
    QList<User> m_users;
    ContactsTopPeersClassType m_classType;
};

Q_DECLARE_METATYPE(ContactsTopPeers)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const ContactsTopPeers &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, ContactsTopPeers &item);

#endif // LQTG_TYPE_CONTACTSTOPPEERS
