// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "inputpeernotifyevents.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

InputPeerNotifyEvents::InputPeerNotifyEvents(InputPeerNotifyEventsClassType classType, InboundPkt *in) :
    m_classType(classType)
{
    if(in) fetch(in);
}

InputPeerNotifyEvents::InputPeerNotifyEvents(InboundPkt *in) :
    m_classType(typeInputPeerNotifyEventsEmpty)
{
    fetch(in);
}

InputPeerNotifyEvents::InputPeerNotifyEvents(const Null &null) :
    TelegramTypeObject(null),
    m_classType(typeInputPeerNotifyEventsEmpty)
{
}

InputPeerNotifyEvents::~InputPeerNotifyEvents() {
}

bool InputPeerNotifyEvents::operator ==(const InputPeerNotifyEvents &b) const {
    return m_classType == b.m_classType;
}

void InputPeerNotifyEvents::setClassType(InputPeerNotifyEvents::InputPeerNotifyEventsClassType classType) {
    m_classType = classType;
}

InputPeerNotifyEvents::InputPeerNotifyEventsClassType InputPeerNotifyEvents::classType() const {
    return m_classType;
}

bool InputPeerNotifyEvents::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeInputPeerNotifyEventsEmpty: {
        m_classType = static_cast<InputPeerNotifyEventsClassType>(x);
        return true;
    }
        break;
    
    case typeInputPeerNotifyEventsAll: {
        m_classType = static_cast<InputPeerNotifyEventsClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool InputPeerNotifyEvents::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeInputPeerNotifyEventsEmpty: {
        return true;
    }
        break;
    
    case typeInputPeerNotifyEventsAll: {
        return true;
    }
        break;
    
    default:
        return false;
    }
}

QByteArray InputPeerNotifyEvents::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

QDataStream &operator<<(QDataStream &stream, const InputPeerNotifyEvents &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case InputPeerNotifyEvents::typeInputPeerNotifyEventsEmpty:
        
        break;
    case InputPeerNotifyEvents::typeInputPeerNotifyEventsAll:
        
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, InputPeerNotifyEvents &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<InputPeerNotifyEvents::InputPeerNotifyEventsClassType>(type));
    switch(type) {
    case InputPeerNotifyEvents::typeInputPeerNotifyEventsEmpty: {
        
    }
        break;
    case InputPeerNotifyEvents::typeInputPeerNotifyEventsAll: {
        
    }
        break;
    }
    return stream;
}

