// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "peernotifyevents.h"
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

PeerNotifyEvents::PeerNotifyEvents(PeerNotifyEventsType classType, InboundPkt *in) :
    m_classType(classType)
{
    if(in) fetch(in);
}

PeerNotifyEvents::PeerNotifyEvents(InboundPkt *in) :
    m_classType(typePeerNotifyEventsEmpty)
{
    fetch(in);
}

PeerNotifyEvents::PeerNotifyEvents(const Null &null) :
    TelegramTypeObject(null),
    m_classType(typePeerNotifyEventsEmpty)
{
}

PeerNotifyEvents::~PeerNotifyEvents() {
}

bool PeerNotifyEvents::operator ==(const PeerNotifyEvents &b) const {
    return m_classType == b.m_classType;
}

void PeerNotifyEvents::setClassType(PeerNotifyEvents::PeerNotifyEventsType classType) {
    m_classType = classType;
}

PeerNotifyEvents::PeerNotifyEventsType PeerNotifyEvents::classType() const {
    return m_classType;
}

bool PeerNotifyEvents::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typePeerNotifyEventsEmpty: {
        m_classType = static_cast<PeerNotifyEventsType>(x);
        return true;
    }
        break;
    
    case typePeerNotifyEventsAll: {
        m_classType = static_cast<PeerNotifyEventsType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

bool PeerNotifyEvents::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typePeerNotifyEventsEmpty: {
        return true;
    }
        break;
    
    case typePeerNotifyEventsAll: {
        return true;
    }
        break;
    
    default:
        return false;
    }
}

QDataStream &operator<<(QDataStream &stream, const PeerNotifyEvents &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case PeerNotifyEvents::typePeerNotifyEventsEmpty:
        
        break;
    case PeerNotifyEvents::typePeerNotifyEventsAll:
        
        break;
    }
    return stream;
}

QDataStream &operator>>(QDataStream &stream, PeerNotifyEvents &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<PeerNotifyEvents::PeerNotifyEventsType>(type));
    switch(type) {
    case PeerNotifyEvents::typePeerNotifyEventsEmpty: {
        
    }
        break;
    case PeerNotifyEvents::typePeerNotifyEventsAll: {
        
    }
        break;
    }
    return stream;
}

