// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_FNC_UPDATES
#define LQTG_FNC_UPDATES

#include "telegramfunctionobject.h"
#include "telegram/types/updatesstate.h"
#include "telegram/types/updatesdifference.h"
#include <QtGlobal>
#include "telegram/types/updateschanneldifference.h"
#include "telegram/types/inputchannel.h"
#include "telegram/types/channelmessagesfilter.h"

namespace Tg {
namespace Functions {

class LIBQTELEGRAMSHARED_EXPORT Updates : public TelegramFunctionObject
{
public:
    enum UpdatesFunction {
        fncUpdatesGetState = 0xedd4882a,
        fncUpdatesGetDifference = 0xa041495,
        fncUpdatesGetChannelDifference = 0xbb32d7c0
    };

    Updates();
    virtual ~Updates();

    static bool getState(OutboundPkt *out);
    static UpdatesState getStateResult(InboundPkt *in);

    static bool getDifference(OutboundPkt *out, qint32 pts, qint32 date, qint32 qts);
    static UpdatesDifference getDifferenceResult(InboundPkt *in);

    static bool getChannelDifference(OutboundPkt *out, const InputChannel &channel, const ChannelMessagesFilter &filter, qint32 pts, qint32 limit);
    static UpdatesChannelDifference getChannelDifferenceResult(InboundPkt *in);

};

}
}

#endif // LQTG_FNC_UPDATES
