// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_MESSAGESPEERDIALOGS_OBJECT
#define LQTG_TYPE_MESSAGESPEERDIALOGS_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/messagespeerdialogs.h"

#include <QPointer>
#include "updatesstateobject.h"

class LIBQTELEGRAMSHARED_EXPORT MessagesPeerDialogsObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(MessagesPeerDialogsClassType)
    Q_PROPERTY(QList<Chat> chats READ chats WRITE setChats NOTIFY chatsChanged)
    Q_PROPERTY(QList<Dialog> dialogs READ dialogs WRITE setDialogs NOTIFY dialogsChanged)
    Q_PROPERTY(QList<Message> messages READ messages WRITE setMessages NOTIFY messagesChanged)
    Q_PROPERTY(UpdatesStateObject* state READ state WRITE setState NOTIFY stateChanged)
    Q_PROPERTY(QList<User> users READ users WRITE setUsers NOTIFY usersChanged)
    Q_PROPERTY(MessagesPeerDialogs core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum MessagesPeerDialogsClassType {
        TypeMessagesPeerDialogs
    };

    MessagesPeerDialogsObject(const MessagesPeerDialogs &core, QObject *parent = 0);
    MessagesPeerDialogsObject(QObject *parent = 0);
    virtual ~MessagesPeerDialogsObject();

    void setChats(const QList<Chat> &chats);
    QList<Chat> chats() const;

    void setDialogs(const QList<Dialog> &dialogs);
    QList<Dialog> dialogs() const;

    void setMessages(const QList<Message> &messages);
    QList<Message> messages() const;

    void setState(UpdatesStateObject* state);
    UpdatesStateObject* state() const;

    void setUsers(const QList<User> &users);
    QList<User> users() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const MessagesPeerDialogs &core);
    MessagesPeerDialogs core() const;

    MessagesPeerDialogsObject &operator =(const MessagesPeerDialogs &b);
    bool operator ==(const MessagesPeerDialogs &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void chatsChanged();
    void dialogsChanged();
    void messagesChanged();
    void stateChanged();
    void usersChanged();

private Q_SLOTS:
    void coreStateChanged();

private:
    QPointer<UpdatesStateObject> m_state;
    MessagesPeerDialogs m_core;
};

inline MessagesPeerDialogsObject::MessagesPeerDialogsObject(const MessagesPeerDialogs &core, QObject *parent) :
    TelegramTypeQObject(parent),
    m_state(0),
    m_core(core)
{
    m_state = new UpdatesStateObject(m_core.state(), this);
    connect(m_state.data(), &UpdatesStateObject::coreChanged, this, &MessagesPeerDialogsObject::coreStateChanged);
}

inline MessagesPeerDialogsObject::MessagesPeerDialogsObject(QObject *parent) :
    TelegramTypeQObject(parent),
    m_state(0),
    m_core()
{
    m_state = new UpdatesStateObject(m_core.state(), this);
    connect(m_state.data(), &UpdatesStateObject::coreChanged, this, &MessagesPeerDialogsObject::coreStateChanged);
}

inline MessagesPeerDialogsObject::~MessagesPeerDialogsObject() {
}

inline void MessagesPeerDialogsObject::setChats(const QList<Chat> &chats) {
    if(m_core.chats() == chats) return;
    m_core.setChats(chats);
    Q_EMIT chatsChanged();
    Q_EMIT coreChanged();
}

inline QList<Chat> MessagesPeerDialogsObject::chats() const {
    return m_core.chats();
}

inline void MessagesPeerDialogsObject::setDialogs(const QList<Dialog> &dialogs) {
    if(m_core.dialogs() == dialogs) return;
    m_core.setDialogs(dialogs);
    Q_EMIT dialogsChanged();
    Q_EMIT coreChanged();
}

inline QList<Dialog> MessagesPeerDialogsObject::dialogs() const {
    return m_core.dialogs();
}

inline void MessagesPeerDialogsObject::setMessages(const QList<Message> &messages) {
    if(m_core.messages() == messages) return;
    m_core.setMessages(messages);
    Q_EMIT messagesChanged();
    Q_EMIT coreChanged();
}

inline QList<Message> MessagesPeerDialogsObject::messages() const {
    return m_core.messages();
}

inline void MessagesPeerDialogsObject::setState(UpdatesStateObject* state) {
    if(m_state == state) return;
    if(m_state) delete m_state;
    m_state = state;
    if(m_state) {
        m_state->setParent(this);
        m_core.setState(m_state->core());
        connect(m_state.data(), &UpdatesStateObject::coreChanged, this, &MessagesPeerDialogsObject::coreStateChanged);
    }
    Q_EMIT stateChanged();
    Q_EMIT coreChanged();
}

inline UpdatesStateObject*  MessagesPeerDialogsObject::state() const {
    return m_state;
}

inline void MessagesPeerDialogsObject::setUsers(const QList<User> &users) {
    if(m_core.users() == users) return;
    m_core.setUsers(users);
    Q_EMIT usersChanged();
    Q_EMIT coreChanged();
}

inline QList<User> MessagesPeerDialogsObject::users() const {
    return m_core.users();
}

inline MessagesPeerDialogsObject &MessagesPeerDialogsObject::operator =(const MessagesPeerDialogs &b) {
    if(m_core == b) return *this;
    m_core = b;
    m_state->setCore(b.state());

    Q_EMIT chatsChanged();
    Q_EMIT dialogsChanged();
    Q_EMIT messagesChanged();
    Q_EMIT stateChanged();
    Q_EMIT usersChanged();
    Q_EMIT coreChanged();
    return *this;
}

inline bool MessagesPeerDialogsObject::operator ==(const MessagesPeerDialogs &b) const {
    return m_core == b;
}

inline void MessagesPeerDialogsObject::setClassType(quint32 classType) {
    MessagesPeerDialogs::MessagesPeerDialogsClassType result;
    switch(classType) {
    case TypeMessagesPeerDialogs:
        result = MessagesPeerDialogs::typeMessagesPeerDialogs;
        break;
    default:
        result = MessagesPeerDialogs::typeMessagesPeerDialogs;
        break;
    }

    if(m_core.classType() == result) return;
    m_core.setClassType(result);
    Q_EMIT classTypeChanged();
    Q_EMIT coreChanged();
}

inline quint32 MessagesPeerDialogsObject::classType() const {
    int result;
    switch(static_cast<qint64>(m_core.classType())) {
    case MessagesPeerDialogs::typeMessagesPeerDialogs:
        result = TypeMessagesPeerDialogs;
        break;
    default:
        result = TypeMessagesPeerDialogs;
        break;
    }

    return result;
}

inline void MessagesPeerDialogsObject::setCore(const MessagesPeerDialogs &core) {
    operator =(core);
}

inline MessagesPeerDialogs MessagesPeerDialogsObject::core() const {
    return m_core;
}

inline void MessagesPeerDialogsObject::coreStateChanged() {
    if(m_core.state() == m_state->core()) return;
    m_core.setState(m_state->core());
    Q_EMIT stateChanged();
    Q_EMIT coreChanged();
}

#endif // LQTG_TYPE_MESSAGESPEERDIALOGS_OBJECT
