// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "messagemediaobject.h"

MessageMediaObject::MessageMediaObject(const MessageMedia &core, QObject *parent) :
    TelegramTypeQObject(parent),
    m_audio(0),
    m_document(0),
    m_geo(0),
    m_photo(0),
    m_video(0),
    m_webpage(0),
    m_core(core)
{
    m_audio = new AudioObject(m_core.audio(), this);
    connect(m_audio.data(), &AudioObject::coreChanged, this, &MessageMediaObject::coreAudioChanged);
    m_document = new DocumentObject(m_core.document(), this);
    connect(m_document.data(), &DocumentObject::coreChanged, this, &MessageMediaObject::coreDocumentChanged);
    m_geo = new GeoPointObject(m_core.geo(), this);
    connect(m_geo.data(), &GeoPointObject::coreChanged, this, &MessageMediaObject::coreGeoChanged);
    m_photo = new PhotoObject(m_core.photo(), this);
    connect(m_photo.data(), &PhotoObject::coreChanged, this, &MessageMediaObject::corePhotoChanged);
    m_video = new VideoObject(m_core.video(), this);
    connect(m_video.data(), &VideoObject::coreChanged, this, &MessageMediaObject::coreVideoChanged);
    m_webpage = new WebPageObject(m_core.webpage(), this);
    connect(m_webpage.data(), &WebPageObject::coreChanged, this, &MessageMediaObject::coreWebpageChanged);
}

MessageMediaObject::MessageMediaObject(QObject *parent) :
    TelegramTypeQObject(parent),
    m_audio(0),
    m_document(0),
    m_geo(0),
    m_photo(0),
    m_video(0),
    m_webpage(0),
    m_core()
{
    m_audio = new AudioObject(m_core.audio(), this);
    connect(m_audio.data(), &AudioObject::coreChanged, this, &MessageMediaObject::coreAudioChanged);
    m_document = new DocumentObject(m_core.document(), this);
    connect(m_document.data(), &DocumentObject::coreChanged, this, &MessageMediaObject::coreDocumentChanged);
    m_geo = new GeoPointObject(m_core.geo(), this);
    connect(m_geo.data(), &GeoPointObject::coreChanged, this, &MessageMediaObject::coreGeoChanged);
    m_photo = new PhotoObject(m_core.photo(), this);
    connect(m_photo.data(), &PhotoObject::coreChanged, this, &MessageMediaObject::corePhotoChanged);
    m_video = new VideoObject(m_core.video(), this);
    connect(m_video.data(), &VideoObject::coreChanged, this, &MessageMediaObject::coreVideoChanged);
    m_webpage = new WebPageObject(m_core.webpage(), this);
    connect(m_webpage.data(), &WebPageObject::coreChanged, this, &MessageMediaObject::coreWebpageChanged);
}

MessageMediaObject::~MessageMediaObject() {
}

void MessageMediaObject::setAddress(const QString &address) {
    if(m_core.address() == address) return;
    m_core.setAddress(address);
    Q_EMIT addressChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::address() const {
    return m_core.address();
}

void MessageMediaObject::setAudio(AudioObject* audio) {
    if(m_audio == audio) return;
    if(m_audio) delete m_audio;
    m_audio = audio;
    if(m_audio) {
        m_audio->setParent(this);
        m_core.setAudio(m_audio->core());
        connect(m_audio.data(), &AudioObject::coreChanged, this, &MessageMediaObject::coreAudioChanged);
    }
    Q_EMIT audioChanged();
    Q_EMIT coreChanged();
}

AudioObject*  MessageMediaObject::audio() const {
    return m_audio;
}

void MessageMediaObject::setCaption(const QString &caption) {
    if(m_core.caption() == caption) return;
    m_core.setCaption(caption);
    Q_EMIT captionChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::caption() const {
    return m_core.caption();
}

void MessageMediaObject::setDocument(DocumentObject* document) {
    if(m_document == document) return;
    if(m_document) delete m_document;
    m_document = document;
    if(m_document) {
        m_document->setParent(this);
        m_core.setDocument(m_document->core());
        connect(m_document.data(), &DocumentObject::coreChanged, this, &MessageMediaObject::coreDocumentChanged);
    }
    Q_EMIT documentChanged();
    Q_EMIT coreChanged();
}

DocumentObject*  MessageMediaObject::document() const {
    return m_document;
}

void MessageMediaObject::setFirstName(const QString &firstName) {
    if(m_core.firstName() == firstName) return;
    m_core.setFirstName(firstName);
    Q_EMIT firstNameChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::firstName() const {
    return m_core.firstName();
}

void MessageMediaObject::setGeo(GeoPointObject* geo) {
    if(m_geo == geo) return;
    if(m_geo) delete m_geo;
    m_geo = geo;
    if(m_geo) {
        m_geo->setParent(this);
        m_core.setGeo(m_geo->core());
        connect(m_geo.data(), &GeoPointObject::coreChanged, this, &MessageMediaObject::coreGeoChanged);
    }
    Q_EMIT geoChanged();
    Q_EMIT coreChanged();
}

GeoPointObject*  MessageMediaObject::geo() const {
    return m_geo;
}

void MessageMediaObject::setLastName(const QString &lastName) {
    if(m_core.lastName() == lastName) return;
    m_core.setLastName(lastName);
    Q_EMIT lastNameChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::lastName() const {
    return m_core.lastName();
}

void MessageMediaObject::setPhoneNumber(const QString &phoneNumber) {
    if(m_core.phoneNumber() == phoneNumber) return;
    m_core.setPhoneNumber(phoneNumber);
    Q_EMIT phoneNumberChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::phoneNumber() const {
    return m_core.phoneNumber();
}

void MessageMediaObject::setPhoto(PhotoObject* photo) {
    if(m_photo == photo) return;
    if(m_photo) delete m_photo;
    m_photo = photo;
    if(m_photo) {
        m_photo->setParent(this);
        m_core.setPhoto(m_photo->core());
        connect(m_photo.data(), &PhotoObject::coreChanged, this, &MessageMediaObject::corePhotoChanged);
    }
    Q_EMIT photoChanged();
    Q_EMIT coreChanged();
}

PhotoObject*  MessageMediaObject::photo() const {
    return m_photo;
}

void MessageMediaObject::setProvider(const QString &provider) {
    if(m_core.provider() == provider) return;
    m_core.setProvider(provider);
    Q_EMIT providerChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::provider() const {
    return m_core.provider();
}

void MessageMediaObject::setTitle(const QString &title) {
    if(m_core.title() == title) return;
    m_core.setTitle(title);
    Q_EMIT titleChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::title() const {
    return m_core.title();
}

void MessageMediaObject::setUserId(qint32 userId) {
    if(m_core.userId() == userId) return;
    m_core.setUserId(userId);
    Q_EMIT userIdChanged();
    Q_EMIT coreChanged();
}

qint32 MessageMediaObject::userId() const {
    return m_core.userId();
}

void MessageMediaObject::setVenueId(const QString &venueId) {
    if(m_core.venueId() == venueId) return;
    m_core.setVenueId(venueId);
    Q_EMIT venueIdChanged();
    Q_EMIT coreChanged();
}

QString MessageMediaObject::venueId() const {
    return m_core.venueId();
}

void MessageMediaObject::setVideo(VideoObject* video) {
    if(m_video == video) return;
    if(m_video) delete m_video;
    m_video = video;
    if(m_video) {
        m_video->setParent(this);
        m_core.setVideo(m_video->core());
        connect(m_video.data(), &VideoObject::coreChanged, this, &MessageMediaObject::coreVideoChanged);
    }
    Q_EMIT videoChanged();
    Q_EMIT coreChanged();
}

VideoObject*  MessageMediaObject::video() const {
    return m_video;
}

void MessageMediaObject::setWebpage(WebPageObject* webpage) {
    if(m_webpage == webpage) return;
    if(m_webpage) delete m_webpage;
    m_webpage = webpage;
    if(m_webpage) {
        m_webpage->setParent(this);
        m_core.setWebpage(m_webpage->core());
        connect(m_webpage.data(), &WebPageObject::coreChanged, this, &MessageMediaObject::coreWebpageChanged);
    }
    Q_EMIT webpageChanged();
    Q_EMIT coreChanged();
}

WebPageObject*  MessageMediaObject::webpage() const {
    return m_webpage;
}

MessageMediaObject &MessageMediaObject::operator =(const MessageMedia &b) {
    if(m_core == b) return *this;
    m_core = b;
    m_audio->setCore(b.audio());
    m_document->setCore(b.document());
    m_geo->setCore(b.geo());
    m_photo->setCore(b.photo());
    m_video->setCore(b.video());
    m_webpage->setCore(b.webpage());

    Q_EMIT addressChanged();
    Q_EMIT audioChanged();
    Q_EMIT captionChanged();
    Q_EMIT documentChanged();
    Q_EMIT firstNameChanged();
    Q_EMIT geoChanged();
    Q_EMIT lastNameChanged();
    Q_EMIT phoneNumberChanged();
    Q_EMIT photoChanged();
    Q_EMIT providerChanged();
    Q_EMIT titleChanged();
    Q_EMIT userIdChanged();
    Q_EMIT venueIdChanged();
    Q_EMIT videoChanged();
    Q_EMIT webpageChanged();
    Q_EMIT coreChanged();
    return *this;
}

bool MessageMediaObject::operator ==(const MessageMedia &b) const {
    return m_core == b;
}

void MessageMediaObject::setClassType(quint32 classType) {
    MessageMedia::MessageMediaType result;
    switch(classType) {
    case TypeMessageMediaEmpty:
        result = MessageMedia::typeMessageMediaEmpty;
        break;
    case TypeMessageMediaPhoto:
        result = MessageMedia::typeMessageMediaPhoto;
        break;
    case TypeMessageMediaVideo:
        result = MessageMedia::typeMessageMediaVideo;
        break;
    case TypeMessageMediaGeo:
        result = MessageMedia::typeMessageMediaGeo;
        break;
    case TypeMessageMediaContact:
        result = MessageMedia::typeMessageMediaContact;
        break;
    case TypeMessageMediaUnsupported:
        result = MessageMedia::typeMessageMediaUnsupported;
        break;
    case TypeMessageMediaDocument:
        result = MessageMedia::typeMessageMediaDocument;
        break;
    case TypeMessageMediaAudio:
        result = MessageMedia::typeMessageMediaAudio;
        break;
    case TypeMessageMediaWebPage:
        result = MessageMedia::typeMessageMediaWebPage;
        break;
    case TypeMessageMediaVenue:
        result = MessageMedia::typeMessageMediaVenue;
        break;
    default:
        result = MessageMedia::typeMessageMediaEmpty;
        break;
    }

    if(m_core.classType() == result) return;
    m_core.setClassType(result);
    Q_EMIT classTypeChanged();
    Q_EMIT coreChanged();
}

quint32 MessageMediaObject::classType() const {
    int result;
    switch(static_cast<qint64>(m_core.classType())) {
    case MessageMedia::typeMessageMediaEmpty:
        result = TypeMessageMediaEmpty;
        break;
    case MessageMedia::typeMessageMediaPhoto:
        result = TypeMessageMediaPhoto;
        break;
    case MessageMedia::typeMessageMediaVideo:
        result = TypeMessageMediaVideo;
        break;
    case MessageMedia::typeMessageMediaGeo:
        result = TypeMessageMediaGeo;
        break;
    case MessageMedia::typeMessageMediaContact:
        result = TypeMessageMediaContact;
        break;
    case MessageMedia::typeMessageMediaUnsupported:
        result = TypeMessageMediaUnsupported;
        break;
    case MessageMedia::typeMessageMediaDocument:
        result = TypeMessageMediaDocument;
        break;
    case MessageMedia::typeMessageMediaAudio:
        result = TypeMessageMediaAudio;
        break;
    case MessageMedia::typeMessageMediaWebPage:
        result = TypeMessageMediaWebPage;
        break;
    case MessageMedia::typeMessageMediaVenue:
        result = TypeMessageMediaVenue;
        break;
    default:
        result = TypeMessageMediaEmpty;
        break;
    }

    return result;
}

void MessageMediaObject::setCore(const MessageMedia &core) {
    operator =(core);
}

MessageMedia MessageMediaObject::core() const {
    return m_core;
}

void MessageMediaObject::coreAudioChanged() {
    if(m_core.audio() == m_audio->core()) return;
    m_core.setAudio(m_audio->core());
    Q_EMIT audioChanged();
    Q_EMIT coreChanged();
}

void MessageMediaObject::coreDocumentChanged() {
    if(m_core.document() == m_document->core()) return;
    m_core.setDocument(m_document->core());
    Q_EMIT documentChanged();
    Q_EMIT coreChanged();
}

void MessageMediaObject::coreGeoChanged() {
    if(m_core.geo() == m_geo->core()) return;
    m_core.setGeo(m_geo->core());
    Q_EMIT geoChanged();
    Q_EMIT coreChanged();
}

void MessageMediaObject::corePhotoChanged() {
    if(m_core.photo() == m_photo->core()) return;
    m_core.setPhoto(m_photo->core());
    Q_EMIT photoChanged();
    Q_EMIT coreChanged();
}

void MessageMediaObject::coreVideoChanged() {
    if(m_core.video() == m_video->core()) return;
    m_core.setVideo(m_video->core());
    Q_EMIT videoChanged();
    Q_EMIT coreChanged();
}

void MessageMediaObject::coreWebpageChanged() {
    if(m_core.webpage() == m_webpage->core()) return;
    m_core.setWebpage(m_webpage->core());
    Q_EMIT webpageChanged();
    Q_EMIT coreChanged();
}

